

USE [master]
GO

CREATE DATABASE [THINDB] COLLATE Latin1_General_CI_AS_KS_WS
GO

ALTER DATABASE [THINDB] MODIFY FILE
( NAME = N'THINDB', FILEGROWTH = 65536KB )
GO

ALTER DATABASE [THINDB] MODIFY FILE
( NAME = N'THINDB_log', FILEGROWTH = 65536KB )
GO

ALTER DATABASE [THINDB] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [THINDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [THINDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [THINDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [THINDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [THINDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [THINDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [THINDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [THINDB] SET AUTO_SHRINK ON 
GO
ALTER DATABASE [THINDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [THINDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [THINDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [THINDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [THINDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [THINDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [THINDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [THINDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [THINDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [THINDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [THINDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [THINDB] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO
ALTER DATABASE [THINDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [THINDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [THINDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [THINDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [THINDB] SET  MULTI_USER 
GO
ALTER DATABASE [THINDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [THINDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [THINDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [THINDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [THINDB] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'THINDB', N'ON'
GO
ALTER DATABASE [THINDB] SET QUERY_STORE = ON
GO
/*ALTER DATABASE [THINDB]
SET AUTOMATIC_TUNING ( FORCE_LAST_GOOD_PLAN = ON ); */
USE [THINDB]
GO

USE [master]
GO
ALTER DATABASE [THINDB] SET  READ_WRITE 
GO

USE [master]
GO

