name: LTS Update and Test NuGet Archive

on:
  push:
    branches:
      - "main"

jobs:
  build:
    if: github.repository == 'IPA-CyberLab/IPA-DN-ThinController-Private'
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        dotnet-version: ["6.0"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}




      - name: NuGet Restore Test with lts-nuget-archive1
        run: |
             dotnet nuget locals all --clear
             dotnet restore IPA-DN-ThinController-Private-VS2022.sln --configfile ${NUGET_CONFIG}
             dotnet restore IPA-DN-ThinWebClient-Private-VS2022.sln --configfile ${NUGET_CONFIG}
        shell: bash
        env:
          NUGET_CONFIG: submodules/IPA-DN-Cores/Cores.NET/Misc/220626_LtsNugetArchiveConfig/lts-nuget-archive1.config




      - name: NuGet Restore Test with lts-nuget-archive2
        run: |
             dotnet nuget locals all --clear
             dotnet restore IPA-DN-ThinController-Private-VS2022.sln --configfile ${NUGET_CONFIG}
             dotnet restore IPA-DN-ThinWebClient-Private-VS2022.sln --configfile ${NUGET_CONFIG}
        shell: bash
        env:
          NUGET_CONFIG: submodules/IPA-DN-Cores/Cores.NET/Misc/220626_LtsNugetArchiveConfig/lts-nuget-archive2.config




      - name: NuGet Restore Test with lts-nuget-archive3
        run: |
             dotnet nuget locals all --clear
             dotnet restore IPA-DN-ThinController-Private-VS2022.sln --configfile ${NUGET_CONFIG}
             dotnet restore IPA-DN-ThinWebClient-Private-VS2022.sln --configfile ${NUGET_CONFIG}
        shell: bash
        env:
          NUGET_CONFIG: submodules/IPA-DN-Cores/Cores.NET/Misc/220626_LtsNugetArchiveConfig/lts-nuget-archive3.config




      - name: Build Debug IPA-DN-ThinController-Private-VS2022.sln
        run: dotnet build -c Debug -v normal IPA-DN-ThinController-Private-VS2022.sln

      - name: Build Release IPA-DN-ThinController-Private-VS2022.sln
        run: dotnet build -c Release -v normal IPA-DN-ThinController-Private-VS2022.sln





      - name: Build Debug IPA-DN-ThinWebClient-Private-VS2022.sln
        run: dotnet build -c Debug -v normal IPA-DN-ThinWebClient-Private-VS2022.sln

      - name: Build Release IPA-DN-ThinWebClient-Private-VS2022.sln
        run: dotnet build -c Release -v normal IPA-DN-ThinWebClient-Private-VS2022.sln



