name: Build and Test

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 15

    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet-version: ["6.0"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}




      - name: Build Debug IPA-DN-ThinController-Private-VS2022.sln
        run: dotnet build -c Debug IPA-DN-ThinController-Private-VS2022.sln

      - name: Test Debug IPA-DN-ThinController-Private-VS2022.sln
        run: dotnet test -c Debug -v normal --logger:"console;verbosity=detailed" IPA-DN-ThinController-Private-VS2022.sln



      - name: Build Release IPA-DN-ThinController-Private-VS2022.sln
        run: dotnet build -c Release IPA-DN-ThinController-Private-VS2022.sln

      - name: Test Release IPA-DN-ThinController-Private-VS2022.sln
        run: dotnet test -c Release -v normal --logger:"console;verbosity=detailed" IPA-DN-ThinController-Private-VS2022.sln



      - name: Build Debug IPA-DN-ThinWebClient-Private-VS2022.sln
        run: dotnet build -c Debug -v normal IPA-DN-ThinWebClient-Private-VS2022.sln

      - name: Build Release IPA-DN-ThinWebClient-Private-VS2022.sln
        run: dotnet build -c Release -v normal IPA-DN-ThinWebClient-Private-VS2022.sln



